apiVersion: v1
kind: PersistentVolume
metadata:
  name: skywalking-elk-cncf
spec:
  capacity:
    storage: 30Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-r1-elk-cncf
  local:
    path: /mnt/data/skywalking-elk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - demo1


