apiVersion: v1
kind: ConfigMap
data:
  config: |-
    database=mysql
    spring.datasource.url=jdbc:mysql://mysql/petclinic
    spring.datasource.username=root
    spring.datasource.password=petclinic
    spring.datasource.schema=classpath*:db/${database}/schema.sql
    spring.datasource.data=classpath*:db/${database}/data.sql
    spring.thymeleaf.mode=HTML
    spring.jpa.hibernate.ddl-auto=none
    spring.messages.basename=messages/messages
    management.endpoints.web.base-path=/manage
    management.endpoints.web.exposure.include=*
    logging.level.org.springframework=INFO
    spring.profiles.active=production
metadata:
  name: petclinic-config
  labels:
    name: petclinic-config
  namespace: sample-petclinic
  
